---
# Install Blocks
# Ubuntu
- name: "{{ ansible_facts.distribution }}: install elasticsearch"
  block:
    - name: Add elasticsearch apt repository key.
      get_url:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        dest: /etc/apt/trusted.gpg.d/elasticsearch.asc
        mode: '0644'
        force: true

    - name: add elasticsearch repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/elasticsearch.asc] https://artifacts.elastic.co/packages/8.x/apt stable main
        state: present
        filename: elasticsearch
        update_cache: true

    - name: install elasticsearch version {{ es_version }}
      apt:
        name: elasticsearch={{ es_version }}
        state: present
  when: ansible_facts.distribution == 'Ubuntu'
  tags: install
# RedHat
- name:  "{{ ansible_facts.distribution }}: install elasticsearch"
  block:
    - name: enable 
      yum_repository:
        name: Elasticsearch
        description:
        baseurl: "https://artifacts.elastic.co/packages/{{ es_version }}/yum"
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: install elasticsearch version {{ es_version }}
      yum:
        name: "elasticsearch-{{ es_version }}"
        state: present
  when: ansible_facts.distribution == 'RedHat'
  tags: install

# Uninstall block
# Ubuntu
- name: "Ubuntu: remove elasticsearch"
  block:
    - name: "[ Ubuntu ] remove elasticsearch version {{ es_version }}"
      apt:
        name: "elasticsearch={{ es_version }}"
        state: absent
  when: ansible_facts.distribution == 'Ubuntu'
  tags: remove

- name: "RedHat: remove elasticsearch"
  block:
    - name: "[ RedHat ]remove elasticsearch version {{ es_version }}"
      yum:
        name: "elasticsearch-{{ es_version }}"
        state: absent
  when: ansible_facts.distribution == 'RedHat'
  tags: remove
