---
- name: Load OS-specific default variables
  set_fact:
    role_default_vars: |
        {{ lookup('file', '../defaults/' + ansible_facts.distribution + '.yml')|from_yaml }}

- name: debug
  debug:
    msg: "{{ ansible_facts.keys() }}"
- name: debug
  debug:
    msg: "{{ ansible_facts.distribution }}"
- name: debug
  debug:
    msg: "{{ ansible_distribution_release }}"
    
- name: install elasticsearch
  include_tasks:
    file: elasticsearch-install.yml
  tags:
    - install
    - remove

- name: configure Elasticsearch
  include_tasks:
    file: elasticsearch-configure.yml
    apply:
      tags:
        - configure
  tags:
    - configure

- name: start and enable elasticsearch
  service:
    name: elasticsearch.service
    enabled: true
    state: started


# - name: 
#   uri:
#     url: https://
#     method: get
#     status_code: 200
#   register: resp
